package com.github.alex1304.jdashevents.common;

/**
 * Enumerates common GD events
 * 
 * @author Alex1304
 */
public enum CommonEvents {
	AWARDED_LEVEL_ADDED,
	AWARDED_LEVEL_UPDATED,
	AWARDED_LEVEL_DELETED,

	DAILY_LEVEL_CHANGED,
	WEEKLY_DEMON_CHANGED,
	
	RECENT_LEVEL_ADDED,
	RECENT_LEVEL_UPDATED,
	RECENT_LEVEL_DELETED,

	MAGIC_LEVEL_ADDED,
	MAGIC_LEVEL_UPDATED,
	MAGIC_LEVEL_DELETED,
	
	USER_MODERATOR_GRANTED,
	USER_MODERATOR_REVOKED,
	USER_ELDER_MODERATOR_GRANTED,
	USER_ELDER_MODERATOR_REVOKED;
}
